//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMDatabaseFirstConsoleApp3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OneToManyRelationsDbEntities : DbContext
    {
        public OneToManyRelationsDbEntities()
            : base("name=OneToManyRelationsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new Exception("asdasdad");
        }
    
        public virtual DbSet<Human> Humans { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    }
}
